//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LastProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StudentID { get; set; }
        public string StudentName { get; set; }
        public string Department { get; set; }
        public string Major { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> SupervisorID { get; set; }
        public Nullable<int> UniversityID { get; set; }
    
        public virtual Supervisor Supervisor { get; set; }
        public virtual University University { get; set; }
    }
}
